name: npmClientCI
on: push
jobs:
  ci:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    env:
      EARLY_ACCESS_TOKEN: ${{ secrets.EARLY_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: npm-client/openpluginclient

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: npm-client/openpluginclient

      - name: Build
        run: yarn build
        working-directory: npm-client/openpluginclient

      - name: Lint
        run: yarn lint
        working-directory: npm-client/openpluginclient

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=1
        working-directory: npm-client/openpluginclient
