name: pypiClientCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IS_GITHUB_ACTION: true
      EARLY_ACCESS_TOKEN: ${{ secrets.EARLY_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and check package
      run: |
        cd pypi-client
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Create virtual environment
      run: |
        python -m venv venv

    - name: Install package and pytest
      run: |
        source venv/bin/activate
        pip install pypi-client/dist/*.whl
        pip install pytest

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest pypi-client/tests/ --verbose
